/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VariationService } from "../variation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VariationCreateInput } from "./VariationCreateInput";
import { Variation } from "./Variation";
import { VariationFindManyArgs } from "./VariationFindManyArgs";
import { VariationWhereUniqueInput } from "./VariationWhereUniqueInput";
import { VariationUpdateInput } from "./VariationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VariationControllerBase {
  constructor(
    protected readonly service: VariationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Variation })
  @nestAccessControl.UseRoles({
    resource: "Variation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVariation(
    @common.Body() data: VariationCreateInput
  ): Promise<Variation> {
    return await this.service.createVariation({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        size: true,
        color: true,
        key: true,
        value: true,
        createdBy: true,
        deletedBy: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Variation] })
  @ApiNestedQuery(VariationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Variation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async variations(@common.Req() request: Request): Promise<Variation[]> {
    const args = plainToClass(VariationFindManyArgs, request.query);
    return this.service.variations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        size: true,
        color: true,
        key: true,
        value: true,
        createdBy: true,
        deletedBy: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Variation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Variation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async variation(
    @common.Param() params: VariationWhereUniqueInput
  ): Promise<Variation | null> {
    const result = await this.service.variation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        size: true,
        color: true,
        key: true,
        value: true,
        createdBy: true,
        deletedBy: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Variation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Variation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVariation(
    @common.Param() params: VariationWhereUniqueInput,
    @common.Body() data: VariationUpdateInput
  ): Promise<Variation | null> {
    try {
      return await this.service.updateVariation({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          size: true,
          color: true,
          key: true,
          value: true,
          createdBy: true,
          deletedBy: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Variation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Variation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVariation(
    @common.Param() params: VariationWhereUniqueInput
  ): Promise<Variation | null> {
    try {
      return await this.service.deleteVariation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          size: true,
          color: true,
          key: true,
          value: true,
          createdBy: true,
          deletedBy: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
